spring:
  application:
    name: parking-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/park_member?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 9000


mybatis-plus:
  mapper-locations: io/nebula/parking/mapper/xml/*Mapper.xml
